### ISSUE TITLE
Linux port info iterate returns no info

### ISSUE THREAD

**Issue by FObersteiner** [ZigEmbeddedGroup/serial#31]
Running the list_port_info example on Linux does not bring up anything on my system although I have a USB2Serial device attached.

@lcp5y3 I think these lines should `catch "?"` or something similar, not `continue` (which refers to the while, not the block).

https://github.com/ZigEmbeddedGroup/serial/blob/fea2b764e0522a7d727cfe3616f016af9b9b0b6f/src/serial.zig#L601

Also, the iteration while loop call (L561) can be simplified to `while(try self.iterator.next()) |entry| {` (remove the if / else).

**Comment by lcp5y3** [comment]
I'm agree with you. I not satisfy about this way of doing.
Maybe it's a smarter way, to fill params with default value (something like *"none"* or *"N/A"*) instead of just skipping the port.

About:  *Running the list_port_info example on Linux does not bring up anything on my system although I have a USB2Serial device attached.*
Could you tell me more about your device ?
Could you give me the result of:

```bash
ls -ll /sys/class/tty/yourDevicePort/device/subsystem
```

**Comment by FObersteiner** [comment]
> fill params with default value (something like _"none"_ or _"N/A"_)

`"N/A"` seems good to me; I think this is already used for `hw_id`.

> about your device

it's one of these cheap usb-2-serial converter (works fine btw.). As noted in the OP, replacing the `continue` with a default string (`"N/A"`) works for me; running the info example then prints
```text
Port name: 
 - System location: /dev/ttyUSB0
 - Friendly name: ttyUSB0
 - Description: USB-Serial Controller D
 - Manufacturer: Prolific Technology Inc. 
 - Serial #: N/A
 - HW ID: N/A
 - VID: 0x067B PID: 0x2303
```

**Comment by lcp5y3** [comment]
I've opened a PR #32 to fix this behavior, if you want to check.
